import NavBar from '@/components/nav-bar/nav-bar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
  icons: [
    {
      url: '../assets/favicon.ico',
      rel: 'icon',
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={styles.root}>
      <body className={inter.className}>
        <header className={styles.header}>
          <NavBar />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
